---
obstacles:
  obs1:
    position: [7.5, 0.0, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
    size: [5.0, 5.0, 5.0]
robot:
  size: [2.0, 1.0, 1.0]
  start_position: [0.0, 0.0, 0.0]
  start_orientation: [0.0, 0.0, 0.0, 1.0]
goal:
  position: [14, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0, 1.0]
  size: [2.0, 2.0, 2.0]
