---
obstacles:
  obs1:
    position: [5.0, -7.5, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
    size: [0.5, 7.5, 20.0]
  obs2:
    position: [10.0, 7.5, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
    size: [0.5, 7.5, 20.0]
  obs3:
    position: [7.5, 0.0, 7.5]
    orientation: [0.0, 0.0, 0.0, 1.0]
    size: [0.5, 20, 7.5]
  obs4:
    position: [2.5, 0.0, -7.5]
    orientation: [0.0, 0.0, 0.0, 1.0]
    size: [0.5, 20.0, 7.5]
robot:
  size: [2.0, 1.0, 1.0]
  start_position: [0.0, 0.0, 0.0]
  start_orientation: [0.0, 0.0, 0.0, 1.0]
goal:
  position: [14.5, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0, 1.0]
  size: [1.0, 1.0, 1.0]
