obstacles:
  obs0:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 8.0
    - -3.0
    - -7.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs1:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 1.0
    - -5.0
    - 8.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs2:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 7.0
    - -8.0
    - 8.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs3:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 2.0
    - -8.0
    - 1.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs4:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 8.0
    - -5.0
    - -2.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs5:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 8.0
    - -2.0
    - -8.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs6:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 11.0
    - -8.0
    - -6.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs7:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 3.0
    - 7.0
    - 9.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs8:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 7.0
    - 0.0
    - -1.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs9:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 7.0
    - -3.0
    - -5.0
    size:
    - 1.0
    - 1.0
    - 1.0
robot:
  goal_position:
  - 15.0
  - 15.0
  - 15.0
  size:
  - 2.0
  - 1.0
  - 1.0
  start_orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  start_position:
  - 0.0
  - 0.0
  - 0.0
