---
obstacles:
  obs1:
    position: [5.0, -2.5, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
    size: [0.5, 15.0, 20.0]
  obs2:
    position: [10.0, 2.5, 0.0]
    orientation: [0.0, 0.0, 0.0, 1.0]
    size: [0.5, 15.0, 20.0]
robot:
  size: [2.0, 1.0, 1.0]
  start_position: [0.0, 0.0, 0.0]
  start_orientation: [0.0, 0.0, 0.0, 1.0]
goal:
  position: [14.5, 0.0, 0.0]
  orientation: [0.0, 0.0, 0.0, 1.0]
  size: [1.0, 1.0, 1.0]
