obstacles:
  obs0:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 2.0
    - 5.0
    - -6.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs1:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 12.0
    - -7.0
    - 5.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs10:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 8.0
    - 4.0
    - -5.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs11:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 9.0
    - -8.0
    - 7.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs12:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 6.0
    - 4.0
    - -1.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs13:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 13.0
    - 3.0
    - -5.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs14:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 7.0
    - 6.0
    - -8.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs15:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 3.0
    - 3.0
    - -7.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs16:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 9.0
    - 3.0
    - 9.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs17:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 4.0
    - 4.0
    - -8.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs18:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 12.0
    - -3.0
    - 7.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs19:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 9.0
    - -4.0
    - 7.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs2:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 6.0
    - 9.0
    - -9.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs20:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 1.0
    - -5.0
    - -3.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs21:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 10.0
    - 4.0
    - 5.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs22:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 1.0
    - -4.0
    - 4.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs23:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 14.0
    - 7.0
    - 7.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs24:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 10.0
    - 6.0
    - -3.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs25:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 14.0
    - -5.0
    - -2.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs26:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 10.0
    - 7.0
    - -5.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs27:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 14.0
    - -3.0
    - 2.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs28:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 13.0
    - -4.0
    - -8.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs29:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 7.0
    - 8.0
    - 2.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs3:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 10.0
    - 3.0
    - 6.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs4:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 11.0
    - 2.0
    - -7.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs5:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 5.0
    - -8.0
    - 0.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs6:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 12.0
    - -4.0
    - -3.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs7:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 12.0
    - 1.0
    - -5.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs8:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 13.0
    - 7.0
    - 6.0
    size:
    - 1.0
    - 1.0
    - 1.0
  obs9:
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    position:
    - 6.0
    - 1.0
    - 6.0
    size:
    - 1.0
    - 1.0
    - 1.0
robot:
  goal_position:
  - 15.0
  - 15.0
  - 15.0
  size:
  - 2.0
  - 1.0
  - 1.0
  start_orientation:
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  start_position:
  - 0.0
  - 0.0
  - 0.0
